Opella-XD: Fix line endings in ARC EM file
On Windows Ashling GDBserver requires that XML register file has Windows
line endings. File used to have LF line endings which were causing an error:

Error: Error occured while getting Register settings  from arc-opella-em.xml
Error: XML parser expected '=' after 'SYSTEM' at line 22 of 'arc-opella-em.xml'.

XML files shipped with Opella software have CRLF line endings (as they
should).

This patch also renames filename to arc-v2-cpu.xml to match naming
convention used by Ashling, however this name used instead of
arc-em-cpu.xml, because this file is same for both ARC EM and HS.

Signed-off-by: Anton Kolesov <Anton.Kolesov@synopsys.com>